# -*- coding: utf-8 -*-
"""Amazon Prime TV Shows and Movies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_2Y8t2-1NfolIkyLUroryEonFGPK48V

# **Project Name**    -  Amazon Prime TV Shows and Movies

##### **Project Type**    - EDA
##### **Contribution**    - Individual

# **Project Summary -**

Performed Exploratory Data Analysis (EDA) on Amazon Prime Video movies and TV shows using Python to analyse trends, evaluate key business metrics, and generate insights for data-driven decision-making. The objective of this project is to understand content distribution, audience preferences, and factors influencing content performance on the platform. By applying data cleaning, preprocessing, and visualization techniques, the analysis highlights patterns across genres, ratings, popularity, and age certifications, enabling a clearer understanding of the platform’s content landscape.

**The project utilizes two datasets:**

**`Titles`** – This dataset includes detailed information about movies and TV shows such as unique IDs, runtime, genres, IMDb and TMDb ratings, scores, popularity, votes, age certifications, descriptions, and availability. It serves as the primary source for analyzing content characteristics and performance trends.

**`Credits`** – This dataset provides information about actors and directors, along with the characters they portrayed, mapped using their respective IDs. It helps in understanding the contribution of cast and crew to content and their potential influence on popularity.

Overall, this project demonstrates how EDA can be used to extract meaningful insights and support better decision-making in content-driven platforms.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

By analyzing this dataset, businesses, content creators, and data analysts can uncover key trends that influence subscription growth, user engagement, and content investment strategies in the streaming industry.

We have received some key points from platform stakeholders that need to be analyzed, including:

- **`Content Diversity:`** What genres and categories dominate the platform?
- **`Regional Availability:`** How does content distribution vary across different regions?
- **`Trends Over Time:`** How has Amazon Prime’s content library evolved?
IMDb Ratings & Popularity: What are the highest-rated or most popular shows on the platform?
- What is the distribution of titles by type (Movie vs Show).
- Title count per release year
- Relation between imbd score vs tmdb core
- Actor || Director particepation by volume.
Additionally, we will discover more key factors as we go deeper into the data analysis that affect content delivery and audience engagement on the platform.

#### **Define Your Business Objective?**

In today's fastest-growing streaming industry, we need to analyze the factors that affect the public entertainment thought process and influence them to engage with TV shows or movies for a longer time. In this context, we can raise many questions as Data Analysts or Data Scientists to build models for the platform, such as:

- Does customer engagement depend on a particular actor, director, specific location, or genre?

Or we can dive deeper into the analysis and identify factors like:

- Customer engagement may depend on TV shows’ and movies’ ratings, popularity, and certifications.

By analyzing these factors in depth, we can recommend key insights to the platform’s stakeholders that help them make informed decisions. This can ultimately enhance Amazon Prime’s content library, which is directly proportional to increased customer engagement on the platform.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries
# Import Libraries
import numpy as np
import pandas as pd
import warnings
# Ignore all warnings
warnings.filterwarnings("ignore")

# visual libraries
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

"""### Dataset Loading"""

# Load Dataset
from google.colab import drive
drive.mount('/content/drive')

# Diplay all rows and columns
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)
# Titles dataset
Titles  = pd.read_csv("/content/drive/MyDrive/Amazon Prime TV Shows and Movies EDA/titles.csv.zip")
# Credits dataset
Credits = pd.read_csv("/content/drive/MyDrive/Amazon Prime TV Shows and Movies EDA/credits.csv (1).zip")

# merge both data to get all details of both datasets
Amazon_Prime = pd.merge(Titles,Credits , on= 'id', how='outer')

"""### Dataset First View"""

# Dataset First Look
Amazon_Prime.head()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
print(f"Rows of Amazon_Prime data:{Amazon_Prime.shape[0]}\nColumns of Amazon_Prime data:{Amazon_Prime.shape[1]}")

"""### Dataset Information"""

# Dataset Info
Amazon_Prime.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
print(f"Data shape before dropping duplicates: {Amazon_Prime.shape}")
duplicate = Amazon_Prime.duplicated().sum()
print(f"Duplicate Value Count (full row): {duplicate}")
# drop_duplicates
Amazon_Prime.drop_duplicates(inplace=True)
print(f"Data shape after dropping (full row) duplicates: {Amazon_Prime.shape}")

# Next duplicate on subset
subset_duplicate = Amazon_Prime.duplicated(
    subset=['id','title','person_id','name','character']
).sum()
print(f"Duplicate Count (subset): {subset_duplicate}")

# drop duplicate on subset
Amazon_Prime.drop_duplicates(subset=['id','title','person_id','name','character'], keep='first',inplace=True)
print(f"Data shape after dropping (subset) duplicates: {Amazon_Prime.shape}")
# final check
print(f"final check (row): {Amazon_Prime.duplicated().sum()}")
print(f"final check (subset): {Amazon_Prime.duplicated(subset=['id','title','person_id','name','character']).sum()}")

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
# replace look like null values with proper np.nan to handel efficently
for i in ['missing', 'null', 'miss', 'Not available']:
  Amazon_Prime.replace({i: np.nan},inplace= True)

Amazon_Prime.isnull().mean()*100

# Visualizing the missing values
missing = Amazon_Prime.isnull().mean().sort_values(ascending=False) * 100

fig = px.bar(
    x=missing.index,
    y=missing.values,
    text=missing.round(2),
    labels={"x": "Columns", "y": "Missing (%)"},
    title="Missing Values Percentage"
)

# Amazon Prime style theme
fig.update_layout(
    template="plotly_dark",
    plot_bgcolor="#0F171E",   # Prime dark background
    paper_bgcolor="#0F171E",
    font=dict(color="white"),
    title_font=dict(size=20, color="#00A8E1"),  # Prime blue
)

fig.update_traces(
    marker_color="#00A8E1"  # Prime blue bars
)

fig.update_layout(xaxis_tickangle=-45)

fig.show()

"""#### Steps to handel null values"""

Amazon_Prime.groupby('type')[['imdb_score','imdb_votes','tmdb_score']].median()

# Step's to handel null values

# step: 1
# Drope age_certification(93% null) & seasons(53% null) (not useful for analysis)
Amazon_Prime.drop(['age_certification','seasons'], axis= 1,inplace=True)

# step: 2
"""Drop null values for columns like [description,tmdb_popularity,person_id, name, role]
   bacause these all of individual null values are less then 1% ,
   Since impact is minimal, removing them avoids unnecessary imputation bias"""

Amazon_Prime.dropna(subset=['description','tmdb_popularity','person_id', 'name', 'role'], inplace = True)

# step: 3
# Replace imdb_id  null values with "unknown" as no logical replacement exists
Amazon_Prime['imdb_id']= Amazon_Prime['imdb_id'].fillna('unknown')

# step: 4
"""fill null values for imdb_score , imdb_votes , tmdb_score with there individual median,
   medain is most ideal approch based on (grouped by type) to preserve distribution and reduce skew impact
"""
Amazon_Prime[['imdb_score','imdb_votes','tmdb_score']] = (
    Amazon_Prime.groupby('type')[['imdb_score','imdb_votes','tmdb_score']]
    .transform(lambda x: x.fillna(x.median()))
)

# step: 5
# handel null values for character with context-aware imputation
"""Fill missing 'character' values using the most frequent role per person (grouped by person_id and name)
This preserves contextual relationships and avoids arbitrary imputation like 'Unknown'
Falls back to 'Unknown' only when no valid character information is available"""

Amazon_Prime['character'] = (
    Amazon_Prime.groupby(['person_id','name'])['character']
    .transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown'))
)
#---------------------
# Handel dtype
#---------------------
# Convert imdb_votes --- float64--->---- int64
Amazon_Prime['imdb_votes'] = Amazon_Prime['imdb_votes'].astype('int64')
# Convert person_id flot64---?--- text formate (string-like)
Amazon_Prime['person_id'] = Amazon_Prime['person_id'].astype('object')

# final dataset info
print(f"{Amazon_Prime.info()}")

"""Test data cleaning most important for
Prevents duplicate categoriey and
Required for Machine Learning, models treat text as features:
"""
# Text cleaning with str()---lowercase()---strip()
# Step: 1 for title clean
import pandas as pd

def text_clean(text):
    if pd.isna(text):
        return ""

    text = str(text).lower().strip()

    # remove special characters
    for char in ['~','!','@','#','$','%','^','&','*','(',')','_','+','=','-','[',']','{','}','|','\\',':',';','"','<','>',',','.','/','?']:
        text = text.replace(char, '')


    return text
# Final Implement
for col in ['title','description','name',	'character']:
    Amazon_Prime[col] = Amazon_Prime[col].apply(text_clean)
#----------------------------------------------------------------
# Final adjusment
#----------------------------------------------------------------
# First for title
Amazon_Prime[['title','name','character']] =Amazon_Prime[['title','name','character']].apply(lambda x:x.str.title())

# description
Amazon_Prime['description']= Amazon_Prime['description'].apply(lambda x: x.capitalize())

# Handel genres &	production_countries Final one
def clean_list_column(x):
    if pd.isna(x):
        return []

    x = str(x)

    # Remove brackets and quotes
    x = x.replace('[','').replace(']','').replace("'", "")

    # Split into list
    items = x.split(',')

    cleaned = []
    for item in items:
        item = item.lower().strip()

        # remove digits
        item = ''.join([i for i in item if not i.isdigit()])

        # convert to Title Case
        item = item.title()

        if item:
            cleaned.append(item)

    return cleaned

# Final Implementation
Amazon_Prime['genres'] = Amazon_Prime['genres'].apply(clean_list_column)
Amazon_Prime['production_countries'] = Amazon_Prime['production_countries'].apply(clean_list_column)

#--------------------------------------------------------
# Handel duplicates in production_countries
#--------------------------------------------------------
mapping = {
    'Us': 'USA',
    'US': 'USA',
    'United States Of America': 'USA',

    'Gb': 'UK',
    'United Kingdom': 'UK',

    'In': 'India'
}

Amazon_Prime['production_countries'] = Amazon_Prime['production_countries'].apply(
    lambda lst: [mapping.get(i, i) for i in lst]
)

Amazon_Prime['production_countries'] = Amazon_Prime['production_countries'].apply(
    lambda lst: list(set([mapping.get(i, i) for i in lst]))
)

# Final view
Amazon_Prime.head(3)

"""### What did you know about your dataset?

Initially we have 2 data available **Tiltle & Credit**. We merged them and finally got a full dataset, which we named **Amazon_Prime**, with **rows=125354 & columns=19**.
We finally
- removed duplicates,
- handled null values,
- assigned correct data types
- and most importantly cleaned text data
to avoid duplicacy and make the data consistent, especially for genre & production_countries. Finally, we obtained **rows=124012 & columns=17** in our **Amazon_Prime** data.

####**These are findings:**
We have 4 proper categorical, 4 numeric-like, 1 true numeric, 1 truly unique variable, and 3 different IDs.


- **4 proper categorical:** *type*, *genres*, *production_countries*, *role* : will be used directly as categories for different analyses.


- **4 numeric-like:** *release_year*, *runtime*, *IMDB_score*, *TMDB_score* : these play a significant role because they show both numeric and categorical behavior.


- **None usable variables:** *description*, *title* : no meaningful use of them in our analysis.


- **True numeric:** *imdb_popularity* : the only true numeric variable in our data.


- **3 different ID variables:** *id*, *imdb_id*, *person_id* : no direct use, but can be used for ranking or reference.


- **Unique_id:** *person_id* : helps in identifying and cleaning unique records.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
Amazon_Prime.columns

# Dataset Describe
# First nummeric summery
Nummeric_summary= Amazon_Prime.describe()

# Second categorical/text summery
Object_summary= Amazon_Prime.select_dtypes(include=['object','category']).describe()
Nummeric_summary

Object_summary

"""### Variables Description

- **`id`** → Unique identifier for each title, repeated for multiple cast members

- **`title`** → Name of the movie or TV show
- **`type`** → Indicates whether the content is a MOVIE or SHOW
- **`description`** → Short textual summary of the content
- **`release_year`** → Year in which the content was released
- **`runtime`** → Duration of the content in minutes
- **`genres`** → List of genres associated with the content (multi-label)
- **`production_countries`** → List of countries where the content was produced
- **`imdb_id`** → Unique identifier for the content on IMDb
- **`imdb_score`** → IMDb rating representing audience evaluation
- **`imdb_votes`** → Total number of votes received on IMDb
- **`tmdb_popularity`** → Popularity score based on user engagement on TMDB
- **`tmdb_score`** → Rating of the content on TMDB platform
- **`person_id`** → Unique identifier for each cast or crew member
- **`name`** → Name of the person (actor/crew) involved in the content
- **`character`** → Character played by the person in the content
- **`role`** → Role of the person (e.g., ACTOR, DIRECTOR)

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
for col in Amazon_Prime.columns:
    print(f"({col}) unique values:")

    values = Amazon_Prime[col]

    if values.apply(lambda x: isinstance(x, list)).any():
        values = values.apply(lambda x: ', '.join(x))  # convert list → string

    print(f"{np.sort(values.unique())}\n{'.'*30}")

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.

# First: Create AMprime_Score
# Represents a combined rating (0–10 scale) using IMDb and TMDb scores
Amazon_Prime['AMprime_Score'] = round(
    Amazon_Prime[['imdb_score','tmdb_score']].mean(axis=1), 2
)


# Second: Create AMprime_Popularity
"""
To represent popularity using IMDb votes and TMDb popularity:
- Applied log transformation to imdb_votes to reduce skewness
- Normalized both features to a 0–10 scale using Min-Max scaling
- Combined them using a balanced average
"""

# Step 1: Log transform IMDb votes
Amazon_Prime['votes_log'] = np.log1p(Amazon_Prime['imdb_votes'])

# Step 2: Normalize TMDb popularity
Amazon_Prime['tmdb_pop_norm'] = (
    (Amazon_Prime['tmdb_popularity'] - Amazon_Prime['tmdb_popularity'].min()) /
    (Amazon_Prime['tmdb_popularity'].max() - Amazon_Prime['tmdb_popularity'].min())
) * 10

# Step 3: Normalize votes
Amazon_Prime['votes_norm'] = (
    (Amazon_Prime['votes_log'] - Amazon_Prime['votes_log'].min()) /
    (Amazon_Prime['votes_log'].max() - Amazon_Prime['votes_log'].min())
) * 10

# Step 4: Final popularity score
Amazon_Prime['AMprime_Popularity'] = round(
    0.5 * Amazon_Prime['tmdb_pop_norm'] +
    0.5 * Amazon_Prime['votes_norm'], 2
)

# Step 5: Cleanup
Amazon_Prime.drop(['votes_log', 'tmdb_pop_norm', 'votes_norm'], axis=1, inplace=True)


# Third: Create final AMprime_Rating
"""
Final score combining:
- 60% weight to quality (AMprime_Score)
- 40% weight to popularity (AMprime_Popularity)
"""
Amazon_Prime['AMprime_Rating'] = round(
    0.6 * Amazon_Prime['AMprime_Score'] +
    0.4 * Amazon_Prime['AMprime_Popularity'], 2
)


# Fourth: Categorize release_year into eras
def categorize_era(year):
    if year < 1980:
        return 'Classic Era'
    elif year < 2000:
        return 'Old Era'
    elif year < 2010:
        return 'Early 2000s'
    elif year < 2020:
        return 'Modern Era'
    else:
        return 'Recent Era'

Amazon_Prime['Era'] = Amazon_Prime['release_year'].apply(categorize_era)

# Content Quality Category based on (AMprime_Rating)
Amazon_Prime['Content_Quality'] = 'Average'

# Movies
Amazon_Prime.loc[(Amazon_Prime['type'] == 'MOVIE') & (Amazon_Prime['AMprime_Rating'] >= 7.5), 'Content_Quality'] = 'Excellent'
Amazon_Prime.loc[(Amazon_Prime['type'] == 'MOVIE') & (Amazon_Prime['AMprime_Rating'] >= 6.5) & (Amazon_Prime['AMprime_Rating'] < 7.5), 'Content_Quality'] = 'Good'
Amazon_Prime.loc[(Amazon_Prime['type'] == 'MOVIE') & (Amazon_Prime['AMprime_Rating'] >= 5) & (Amazon_Prime['AMprime_Rating'] < 6.5), 'Content_Quality'] = 'Average'
Amazon_Prime.loc[(Amazon_Prime['type'] == 'MOVIE') & (Amazon_Prime['AMprime_Rating'] < 5), 'Content_Quality'] = 'Poor'

# Shows
Amazon_Prime.loc[(Amazon_Prime['type'] == 'SHOW') & (Amazon_Prime['AMprime_Rating'] >= 8), 'Content_Quality'] = 'Excellent'
Amazon_Prime.loc[(Amazon_Prime['type'] == 'SHOW') & (Amazon_Prime['AMprime_Rating'] >= 7) & (Amazon_Prime['AMprime_Rating'] < 8), 'Content_Quality'] = 'Good'
Amazon_Prime.loc[(Amazon_Prime['type'] == 'SHOW') & (Amazon_Prime['AMprime_Rating'] >= 5.5) & (Amazon_Prime['AMprime_Rating'] < 7), 'Content_Quality'] = 'Average'
Amazon_Prime.loc[(Amazon_Prime['type'] == 'SHOW') & (Amazon_Prime['AMprime_Rating'] < 5.5), 'Content_Quality'] = 'Poor'

# Categorized runtime into segments acc to type
def categorize_runtime(row):
    if row['type'] == 'MOVIE':
        if row['runtime'] < 90:
            return 'Short Movie'
        elif row['runtime'] <= 150:
            return 'Standard Movie'
        else:
            return 'Long Movie'
    else:  # SHOW
        if row['runtime'] < 30:
            return 'Short Episode'
        elif row['runtime'] <= 60:
            return 'Standard Episode'
        else:
            return 'Long Episode'

Amazon_Prime['runtime_category'] = Amazon_Prime.apply(categorize_runtime, axis=1)

# Outliers deduction pipeline
def Outliers_deduction_func(df, group_col, target_col):

    IQR_df = df.groupby(group_col)[target_col].agg(
        Q1=lambda x: x.quantile(0.25),
        Q3=lambda x: x.quantile(0.75),
        Min='min',
        Max='max'
    )

    # IQR
    IQR_df['IQR'] = IQR_df['Q3'] - IQR_df['Q1']

    # Bounds
    IQR_df['LowerBound'] = IQR_df['Q1'] - 1.5 * IQR_df['IQR']
    IQR_df['UpperBound'] = IQR_df['Q3'] + 1.5 * IQR_df['IQR']

    # Detect direction
    IQR_df['LeftOutlier'] = IQR_df['Min'] < IQR_df['LowerBound']
    IQR_df['RightOutlier'] = IQR_df['Max'] > IQR_df['UpperBound']

    # Final status
    def get_status(row):
        if row['LeftOutlier'] and row['RightOutlier']:
            return 'Both'
        elif row['LeftOutlier']:
            return 'Left'
        elif row['RightOutlier']:
            return 'Right'
        else:
            return 'No'

    IQR_df['status'] = IQR_df.apply(get_status, axis=1)

    # Convert True/False to Yes/No (optional)
    IQR_df['LeftOutlier'] = IQR_df['LeftOutlier'].map({True: 'Yes', False: 'No'})
    IQR_df['RightOutlier'] = IQR_df['RightOutlier'].map({True: 'Yes', False: 'No'})

    # Reorder columns
    IQR_df = IQR_df[
        ['Q1','Q3','IQR','Min','LowerBound','Max','UpperBound',
         'LeftOutlier','RightOutlier','status']
    ]

    return IQR_df

 # Outliers deduction For loop for numeric column
cols = ['runtime','imdb_score','tmdb_score','imdb_votes','tmdb_popularity']
for col in cols:
  Outliers_df = Outliers_deduction_func(Amazon_Prime,'type',col)

  print("=" * 60)
  print(f"🔹 Outlier Summary for: {col.upper()}")
  print("=" * 60)
  print(Outliers_df)
  print("\n")

# Outliers Flaging

def overall_outlier_flag(df, group_col, cols):

    df = df.copy()
    outlier_flag = pd.Series(False, index=df.index)

    for col in cols:

        # Step 1: Calculate bounds per group
        bounds = df.groupby(group_col)[col].agg(
            Q1=lambda x: x.quantile(0.25),
            Q3=lambda x: x.quantile(0.75)
        )

        bounds['IQR'] = bounds['Q3'] - bounds['Q1']
        bounds['LowerBound'] = bounds['Q1'] - 1.5 * bounds['IQR']
        bounds['UpperBound'] = bounds['Q3'] + 1.5 * bounds['IQR']

        # Step 2: Map bounds to rows
        temp = df[[group_col, col]].merge(
            bounds[['LowerBound','UpperBound']],
            left_on=group_col,
            right_index=True,
            how='left'
        )

        # Step 3: Check outliers
        col_flag = (temp[col] < temp['LowerBound']) | (temp[col] > temp['UpperBound'])

        # Step 4: Combine flags (OR logic)
        outlier_flag = outlier_flag | col_flag

    # Final column
    df['Any_Outlier'] = outlier_flag.map({True:'Yes', False:'No'})

    return df

# Final implemantation
cols = ['runtime','imdb_votes','tmdb_popularity']

df_final = overall_outlier_flag(Amazon_Prime, 'type', cols)

# Implementation
Amazon_Prime['Any_Outlier'] = overall_outlier_flag(
    Amazon_Prime, 'type', cols
)['Any_Outlier']

# Filter non-outliers
df_no_outliers = Amazon_Prime[Amazon_Prime['Any_Outlier'] == 'No']
# Check Shape
total = Amazon_Prime.shape[0]
clean = df_no_outliers.shape[0]
outliers = total - clean

print("Original Shape:", Amazon_Prime.shape)
print("Without Outliers Shape:", df_no_outliers.shape)

print("Non-Outlier %:", round((clean / total) * 100, 2))
print("Outlier %:", round((outliers / total) * 100, 2))

# Normalized_AMprime data
Normalized_AMprime = Amazon_Prime[Amazon_Prime['Any_Outlier'] == 'Yes']

# ---------------------------------------------------------------------------------
# Grouped category function
def grouped_values(group_col, default_cols='type',df=Amazon_Prime):
  grouped_content = (
      df.groupby([group_col,default_cols])
      .size()
      .unstack(fill_value=0)
      .reset_index())
  return grouped_content

#  Grouped content by categorical variables
cols = ['Era','Content_Quality', 'runtime_category','Any_Outlier']
for col in cols:
  Grouped_Content = grouped_values(col,default_cols='type',df=Amazon_Prime)
  print("=" * 60)
  print(f"🔹 Grouped Summary for: {col.upper()}")
  print("=" * 60)
  print(Grouped_Content)
  print("\n")
#----------------------------------------------------------------------------------
#                             Final view with new veriables.
#----------------------------------------------------------------------------------
df = Amazon_Prime.copy()

fig = make_subplots(
    rows=2, cols=2,
    specs=[
        [{'type':'domain'}, {'type':'domain'}],
        [{'type':'xy'}, {'type':'xy'}]
    ],
    subplot_titles=(
        "Content Quality by Type",
        "Outliers by Type",
        "Era Distribution by Type",
        "Runtime Category by Type"
    )
)

# 1️ Donut: Content Quality
cq = df.groupby(['Content_Quality','type']).size().reset_index(name='Count')
cq['label'] = cq['Content_Quality'] + " - " + cq['type']

fig.add_trace(
    go.Pie(labels=cq['label'], values=cq['Count'], hole=0.5),
    row=1, col=1
)

# 2️ Donut: Outliers
out = df.groupby(['Any_Outlier','type']).size().reset_index(name='Count')
out['label'] = out['Any_Outlier'] + " - " + out['type']

fig.add_trace(
    go.Pie(labels=out['label'], values=out['Count'], hole=0.5),
    row=1, col=2
)

# 3️ Clustered Bar: Era
era = df.groupby(['Era','type']).size().unstack().fillna(0)

fig.add_trace(
    go.Bar(x=era.index, y=era['MOVIE'], name='Movie', marker_color='#00A8E1'),
    row=2, col=1
)

fig.add_trace(
    go.Bar(x=era.index, y=era['SHOW'], name='Show', marker_color='#FF9900'),
    row=2, col=1
)

# 4️ Clustered Bar: Runtime Category
runtime = df.groupby(['runtime_category','type']).size().unstack().fillna(0)

fig.add_trace(
    go.Bar(x=runtime.index, y=runtime['MOVIE'], name='Movie', marker_color='#00A8E1'),
    row=2, col=2
)

fig.add_trace(
    go.Bar(x=runtime.index, y=runtime['SHOW'], name='Show', marker_color='#FF9900'),
    row=2, col=2
)

# Layout (Clustered bars)
fig.update_layout(
    template='plotly_dark',
    plot_bgcolor='#0f171e',
    paper_bgcolor='#0f171e',
    font=dict(color='white'),

    height=650,
    width=950,

    title="Amazon Prime Content Dashboard",
    title_x=0.5,

    barmode='group',
    showlegend=True
)

fig.show()

# SAVE Data
Amazon_Prime.to_csv('/content/drive/MyDrive/Amazon Prime TV Shows and Movies EDA/Prepared_AMprime.csv', index=False)

"""### What all manipulations have you done and insights you found?

To prepare the dataset for advanced analysis, multiple feature engineering techniques were applied to enhance data quality and extract meaningful insights. These transformations helped in creating standardized and comparable metrics for content evaluation.

**Feature Engineering**

- **AMprime_Score:** Created by combining IMDb and TMDb ratings to represent overall content quality on a 0–10 scale.
- **AMprime_Popularity:** Derived using **log transformation** on IMDb votes and **Min-Max normalization** of both votes and TMDb popularity to capture user engagement.
- **AMprime_Rating:** Final composite score calculated using a **weighted average (60% quality, 40% popularity)** for a balanced ranking system.
- **Era & Content_Quality:** Release years were grouped into eras, and content was categorized into quality levels (Excellent, Good, Average, Poor) with different thresholds for movies and shows.
- **runtime_category:** split runtime into category according to
 1) **Movies:** *Sort, standard & long movies.*  
 2) **TV show:** *Sort, standard & long Episode*
- **Any_Outliers:** Flaging outliers data  related to every numeric variable.
####**Conclusion**

These engineered features enable deeper insights into content performance across time, type, and quality segments. They provide a strong foundation for creating impactful visualizations and identifying trends, patterns, and top-performing content in further analysis.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Chart - 1 visualization code
# Numeric variable distribution without outliers
# -------------------------------
# Data
# -------------------------------
num_cols = [
    'imdb_score',
    'tmdb_score',
    'imdb_votes',
    'tmdb_popularity',
    'runtime'
]

df_clean = Amazon_Prime[Amazon_Prime['Any_Outlier'] == 'No']

colors = {'MOVIE': '#00A8E1', 'SHOW': '#FF9900'}

# -------------------------------
# Subplots
# -------------------------------
fig = make_subplots(
    rows=2, cols=3,
    subplot_titles=num_cols,
    horizontal_spacing=0.08,
    vertical_spacing=0.12
)

positions = [(1,1),(1,2),(1,3),(2,1),(2,2)]

# -------------------------------
# Histograms
# -------------------------------
for (col, pos) in zip(num_cols, positions):
    r, c = pos

    for t in ['MOVIE','SHOW']:
        d = df_clean[df_clean['type'] == t]

        fig.add_trace(
            go.Histogram(
                x=d[col],
                name=t,
                marker_color=colors[t],
                opacity=0.6,
                showlegend=(col == num_cols[0])  # legend once
            ),
            row=r, col=c
        )

# -------------------------------
# Layout
# -------------------------------
fig.update_layout(
    barmode='overlay',

    template='plotly_dark',
    plot_bgcolor='#0F171E',
    paper_bgcolor='#0F171E',
    font=dict(color='white'),

    height=700,
    width=1100,

    title="Distribution of Numerical Features (Without Outliers)",
    title_x=0.5,

    # Legend (Bottom Right)
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=0.2,              # low
        xanchor="center",
        x=0.8,
        bgcolor='rgba(0,0,0,0)',  # transparent
        borderwidth=0
    )
)

# Remove grid clutter
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=True, gridcolor='#2A3A4A')

fig.show()

"""##### 1. Why did you pick the specific chart?

Histogram is an ideal chart to understand the spread of the data related to any numeric variable, and helps to identify the central tendency and skewness, meaning whether it is a left, right, or normal distribution.

##### 2. What is/are the insight(s) found from the chart?

IMDb score // TMDb score
- IMDb & TMDb scores are ideally normally distributed for movies with a mean value around 6.

- TV Shows: Left skewed for both IMDb & TMDb scores, and it is a good factor, with a mean value of 7.5.

IMDb votes // TMDb popularity
- Right skewed data; most of the movies have very low IMDb votes and TMDb popularity.
- The count of movies decreases as IMDb votes and TMDb popularity increase.

Runtime:
- Movies: Slightly left skewed data, most movies have lower runtime, with a mean of 90.

- TV Shows: Slightly right skewed with bimodal distribution, meaning 24 and 45 are the popular runtimes for TV shows.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

IMDb score // TMDb score:
- Movies: Distribution is ideally good, but we need to explore how to increase scores; overall, a good significance.

- TV Shows: Are better and show a positive sign of progress, with a 7.5 mean value, indicating people prefer TV shows more than movies.

IMDb votes // TMDb popularity
- It is a negative sign, as the count of movies and shows is high compared to - - IMDb votes and TMDb popularity. We need to discover factors that can increase IMDb votes and TMDb popularity.

Runtime:
- Movies: Graph shows average runtime of movies is 90–100, but can go up to 140 for a good movie length.

- TV Shows: Have an average runtime of around 45 minutes, but can go up to 50–60 as well for a good TV show length.

Hence, it only shows the spread of all numerical variables. We have to discover more factors that an ideal movie should have.

#### Chart - 2
"""

# Chart - 2 visualization code

df = Amazon_Prime.copy()

# --------------------
# Clean
# --------------------
df['type'] = df['type'].str.title()

# Role explode
role_df = df.copy()

role_df['role'] = (
    role_df['role']
    .fillna('')
    .str.split(',')
)

role_df = role_df.explode('role')
role_df['role'] = role_df['role'].str.strip()

# --------------------
# Figure
# --------------------
fig = make_subplots(
    rows=2,
    cols=2,
    specs=[
        [{"type":"domain"}, {"type":"xy"}],
        [{"type":"xy"}, {"type":"domain"}]
    ],
    subplot_titles=(
        "Era by Type",
        "Content Quality by Type",
        "Runtime Category by Type",
        "Top Roles by Type"
    ),
    vertical_spacing=0.15,
    horizontal_spacing=0.12
)

# =====================================================
# 1. Era Donut
# =====================================================
era = (
    df.groupby(['Era','type'])
    .size()
    .reset_index(name='count')
)

for t in era['type'].unique():

    temp = era[era['type'] == t]

    fig.add_trace(
        go.Pie(
            labels=temp['Era'],
            values=temp['count'],
            hole=0.55,
            name=t,
            textinfo='percent',
            domain=dict(x=[0.00, 0.42], y=[0.58, 1])
        )
    )

# =====================================================
# 2. Content Quality
# =====================================================
cq = (
    df.groupby(['Content_Quality','type'])
    .size()
    .reset_index(name='count')
)

bar1 = px.bar(
    cq,
    x='Content_Quality',
    y='count',
    color='type',
    barmode='group'
)

for tr in bar1.data:
    fig.add_trace(tr, row=1, col=2)

# =====================================================
# 3. Runtime Category
# =====================================================
rt = (
    df.groupby(['runtime_category','type'])
    .size()
    .reset_index(name='count')
)

bar2 = px.bar(
    rt,
    x='runtime_category',
    y='count',
    color='type',
    barmode='group'
)

for tr in bar2.data:
    fig.add_trace(tr, row=2, col=1)

# =====================================================
# 4. Role Donut
# =====================================================
top_roles = role_df['role'].value_counts().head(5).index

role = (
    role_df[role_df['role'].isin(top_roles)]
    .groupby(['role','type'])
    .size()
    .reset_index(name='count')
)

for t in role['type'].unique():

    temp = role[role['type'] == t]

    fig.add_trace(
        go.Pie(
            labels=temp['role'],
            values=temp['count'],
            hole=0.55,
            name=t,
            textinfo='percent',
            domain=dict(x=[0.58, 1], y=[0, 0.42])
        )
    )

# --------------------
# Layout
# --------------------
fig.update_layout(
    height=650,
    width=950,
    template='plotly_dark',
    title='Amazon Prime Dashboard',
    title_x=0.5,
    legend_title='Type',
    margin=dict(t=70, b=40, l=30, r=30)
)

fig.show()

"""##### 1. Why did you pick the specific chart?

- Donut Chart: Used to show percentage distribution of Era and Roles.
- Grouped Bar Chart: Best for comparing Movies vs TV Shows across categories.
- Dashboard Layout: Combines multiple insights in one compact view for easy comparison.

##### 2. What is/are the insight(s) found from the chart?

- Modern Era content dominates Amazon Prime, contributing nearly half of the total content library.
- Most content falls under the “Poor” content quality category, especially Movies.
- Standard Movies are the most common runtime category, while TV Shows mainly consist of Standard and Short Episodes.
- ACTOR roles dominate the dataset, whereas DIRECTOR roles represent a very small portion.
- Movies are significantly higher in count compared to TV Shows across most categories.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**`Positive Business Impact:`**
- Modern Era content is highly dominant, showing that Amazon Prime is aligned with current audience preferences and trending content.
- Movies have a much larger catalog than TV Shows, helping attract a wider audience base and increasing viewer engagement.
- Standard-length content is most preferred, indicating strong audience interest in regular movie and episode formats.

**`Negative Growth Insights:`**
- Most content falls under the “Poor” content quality category, which may reduce user satisfaction and platform retention.
- TV Shows are significantly fewer than Movies, limiting binge-watching engagement opportunities.
- Very low diversity in role distribution (mostly ACTOR roles) may reduce deeper content-related insights and personalization opportunities.

#### Chart - 3
"""

# Chart - 2 visualization code
# Content Diversity: What genres and categories dominate the platform?
# Explode genres
df = Amazon_Prime.explode('genres')

# Remove empty values
df = df[df['genres'] != ""]

# Count per genre & type
genre_type_counts = (
    df.groupby(['genres', 'type'])
    .size()
    .reset_index(name='Count')
)

# Get total counts for sorting
total_counts = (
    genre_type_counts.groupby('genres')['Count']
    .sum()
    .sort_values(ascending=False)
)

# Select top 15 genres
top_genres = total_counts.index

# Filter dataset
genre_type_counts = genre_type_counts[
    genre_type_counts['genres'].isin(top_genres)
]

# Plot
fig = px.bar(
    genre_type_counts,
    x='Count',
    y='genres',
    color='type',
    orientation='h',
    barmode='group',
    title='Top Genres by Content Type',
    text='Count',
    color_discrete_map={
        'MOVIE': '#00A8E1',   # Prime blue
        'SHOW': '#FF9900'     # Amazon orange
    }
)

# Amazon Prime Theme
fig.update_layout(
    template='plotly_dark',
    plot_bgcolor='#0f171e',
    paper_bgcolor='#0f171e',
    font=dict(color='white'),
    title_x=0.5,
    height=600,
    xaxis_title='Number of Titles',
    yaxis_title='Genre'
)

# highest at TOP
fig.update_yaxes(
    categoryorder='total ascending'  # ensures proper sorting
)

# Bar styling
fig.update_traces(textposition='outside')

fig.show()

"""##### 1. Why did you pick the specific chart?

Horizonal group bar chart is an ideal chart to visualize the genres distribution w.r.t.  TV Show and Movies. to it will give the clear interpetation for platform groth.

##### 2. What is/are the insight(s) found from the chart?

**Top genres:**
- **Movies:** Drama, Comedy, Thriller, Action & Romence are the top 5 genres of the group.
- **TV Shows:** Drama, Comedy,Action, Scifi & Animation are the top 5 genres of the group.

**Average genres:**

- **Movies:** Eurapian, Scifi, Fantasy, Family, Western are the Average genres of the group.
- **TV Shows:** same for TV Shows.

**Bottom genres**
- **Movies:** Music, war, Animation, Sports are the bottom grnres of the group. Specilty **Reality** is the only genres that not have any movies but have TV Shows.
- **TV Shows:** Sports, Reality, War, music, History are the top bottom genres of the group.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

It is seems Movies and TV Shows have equal likely distribution of genres. Some of the TV show that are much populer the Movies. But not showing any clear interpetation. But we have to discover more factor associated with genres like vots and polularity.

#### Chart - 4
"""

# Chart - 3 visualization code

# Data
year_df = Amazon_Prime.groupby(['release_year','type'])['title'].nunique().reset_index(name='count')
role_df = Amazon_Prime.groupby(['role','type'])['name'].nunique().reset_index(name='count')
type_df = Amazon_Prime.groupby('type')['title'].nunique().reset_index(name='count')

colors = {'MOVIE': '#00A8E1', 'SHOW': '#FF9900'}

# Plot
fig = make_subplots(
    rows=2, cols=2,
    specs=[[{}, {}], [{}, {"type": "domain"}]],
    subplot_titles=(
        "Actor Participation", "Titles per Year",
        "IMDB vs TMDB", "Titles by Type"
    )
)

# Loop (main plots)
for t in ['MOVIE','SHOW']:
    d_year = year_df[year_df['type']==t]
    d_scatter = Amazon_Prime[Amazon_Prime['type']==t]
    d_role = role_df[role_df['type']==t]

    # 1️ Bar (Actor Participation)
    fig.add_bar(
        x=d_role['role'], y=d_role['count'],
        marker_color=colors[t],
        name=t,
        legendgroup=t,
        showlegend=True,
        row=1, col=1
    )

    # 2 Line
    fig.add_scatter(
        x=d_year['release_year'], y=d_year['count'],
        mode='lines+markers',
        name=t,
        line=dict(color=colors[t], width=3),
        legendgroup=t,
        showlegend=False,
        row=1, col=2
    )

    # 3️ Scatter
    fig.add_scatter(
        x=d_scatter['imdb_score'], y=d_scatter['tmdb_score'],
        mode='markers',
        marker=dict(color=colors[t], size=5, opacity=0.6),
        name=t,
        legendgroup=t,
        showlegend=False,
        row=2, col=1
    )

# 4️ Donut (outside loop)
fig.add_trace(go.Pie(
    labels=type_df['type'],
    values=type_df['count'],
    hole=0.5,
    marker=dict(colors=[colors[t] for t in type_df['type']]),
    textinfo='percent+label'
), row=2, col=2)

# Layout
fig.update_layout(
    template='plotly_dark',
    plot_bgcolor='#0F171E',
    paper_bgcolor='#0F171E',
    font=dict(color='#E6F1F5'),
    height=700, width=1000,
    title="Amazon Prime - Business Matrix",
    title_x=0.5,
    legend=dict(orientation="h", y=0.5, x=0.5, xanchor="center")
)

fig.show()

"""##### 1. Why did you pick the specific chart?

**`2x2 Business Question:`**
- Actor || Director participation by volume: Category by volume (grouped bar chart || count)
- Title count per release year: Trend over time (line chart)
- IMDb vs TMDb score relation: Relationship between numeric variables (scatter plot)
- Distribution of titles by show type: Low-category distribution (donut/pie chart)

##### 2. What is/are the insight(s) found from the chart?

- Movies are more dominant than TV Shows in terms of volume.
- TV Shows were introduced later but started growing significantly after 2012.
- However, TV Shows are more popular than Movies.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

As TV shows were introduced later, they are growing rapidly and gaining IMDb & TMDb scores and popularity more than movies. This means people are shifting their interest from movies to TV shows because they are shorter in runtime and easier to watch on a daily basis. Therefore, the platform should focus on TV show quality and their genres.

#### Chart - 5
"""

# Chart - 4 visualization code

# Regional Availability: How does content distribution vary across different regions?
# Explode both columns together
df_exploded = Amazon_Prime.explode('production_countries')

# Remove empty values
df_exploded = df_exploded[df_exploded['production_countries'] != ""]

# Group by country + type
country_type_counts = (
    df_exploded
    .groupby(['production_countries', 'type'])
    .size()
    .unstack(fill_value=0)
)

# Total count for sorting
country_type_counts['total'] = country_type_counts.sum(axis=1)

# Sort by total
country_type_counts = country_type_counts.sort_values(by='total', ascending=False)

# Split data
top_20 = country_type_counts.iloc[:20].sort_values(by='total', ascending=True)
middle_20 = country_type_counts.iloc[58:78].sort_values(by='total', ascending=True)
bottom_20 = country_type_counts.iloc[96:].sort_values(by='total', ascending=True)

# Drop total column for plotting
top_20 = top_20.drop(columns='total')
middle_20 = middle_20.drop(columns='total')
bottom_20 = bottom_20.drop(columns='total')

fig = make_subplots(
    rows=1, cols=3,
    subplot_titles=("Top 20 Countries", "Middle 20 Countries", "Bottom 20 Countries"),
    horizontal_spacing=0.05
)

def add_grouped_bar(data, col):
    for t in data.columns:  # Movie, Show
        fig.add_trace(
            go.Bar(
                x=data[t],
                y=data.index,
                orientation='h',
                name=t,
            ),
            row=1, col=col
        )

# Add traces
add_grouped_bar(top_20, 1)
add_grouped_bar(middle_20, 2)
add_grouped_bar(bottom_20, 3)

# Layout
fig.update_layout(
    title="Production Countries Distribution by Type (Hue = Type)",
    barmode='group',  # IMPORTANT for hue
    template='plotly_dark',
    plot_bgcolor='#0f171e',
    paper_bgcolor='#0f171e',
    font=dict(color='white', size=12),
    width=950,
    height=500,
    margin=dict(l=60, r=20, t=60, b=40)
)

fig.update_yaxes(automargin=True, tickfont=dict(size=8))
fig.update_xaxes(title_text="Number of Titles")

fig.show()

"""##### 1. Why did you pick the specific chart?

Subplots of bar chart ideal chart to show diffrent segtment of distribution for top, average or bottom genress distribution.

##### 2. What is/are the insight(s) found from the chart?

**Top production country**

- **Movies**: country like USA, UK or India are 3 top most production country in top production of movies.
- **TV Shows**: country like USA, UK, CA → Canada, CN →China, India,JP → Japan,AU → Australia top most production country in top production of TV Shows.

**Average production country**
- **Movies**: country like ET → Ethiopia,VA → Vatican City,EG → Egypt are top 3 avrage country related to movies production.
- **TV Shows**: country like SG → Singapore,TR → Turkey, EG → Egypt and UY → Uruguay are are most avrage country related to TV Shows production.

**Bottom production country**
- **Movies**: country like AQ → Antarctica,LY → Libya, PR → Puerto Rico are the top moost bottom country related to movies production.
- **TV Shows**: Seems Approximately 55–57 countries are not producing any TV shows (i.e., they have zero SHOW count).

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Top Production Country**

- **Movies:** Countries like BR → Brazil, KR → South Korea, MX → Mexico, IE → Ireland are in the top production group.
- **TV Shows:** Same countries are also leading in TV show production.

These countries are already doing very well, so there is no need to focus much on them right now.

**Average Production Country**
- Movies: Countries like ET → Ethiopia, VA → Vatican City, EG → Egypt fall in the average category.
- TV Shows: Countries like SG → Singapore, TR → Turkey, EG → Egypt, and UY → Uruguay are in the average group.

These countries are in the middle stage and trying to grow. So, the platform should focus more on them. It will be easier and require less effort to improve them, and they can give good content in the future with better global exposure.

**Bottom Production Country**
- Movies: Countries like AQ → Antarctica, LY → Libya, PR → Puerto Rico are in the lowest production group.
- TV Shows: Around 55–57 countries are not producing any TV shows.

Working on these countries is risky and needs more time and effort.

But we can follow a smart approach by involving actors, directors, and producers from developed countries like USA, UK, India, or Canada to create content in these regions. Also, giving small roles to local people can help them grow slowly.

In this way, we can gradually increase content production and also attract viewers from these countries.

#### Chart - 6
"""

# Chart - 5 visualization code
# -------------------------------
# Aggregation
# -------------------------------
metrics = ['runtime', 'AMprime_Score', 'AMprime_Popularity', 'AMprime_Rating']
stats = ['mean', 'q75', 'max']

agg_df = (
    Amazon_Prime
    .groupby(['Era','type'])[metrics]
    .agg(['mean', lambda x: x.quantile(0.75), 'max'])
)

# flatten column names
agg_df.columns = [
    f"{m}_{s}" if s != '<lambda_0>' else f"{m}_q75"
    for m, s in agg_df.columns
]
agg_df = agg_df.reset_index()

# -------------------------------
# Plot
# -------------------------------
fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=[
        "Runtime", "AMprime Score",
        "AMprime Popularity", "AMprime Rating"
    ]
)

color_map = {
    'MOVIE': ['#00A8E1','#0077B6','#023E8A'],
    'SHOW':  ['#FF9900','#CC7A00','#995C00']
}

for i, metric in enumerate(metrics):
    r, c = i//2 + 1, i%2 + 1

    for t in ['MOVIE','SHOW']:
        d = agg_df[agg_df['type']==t]

        for s, color in zip(stats, color_map[t]):
            fig.add_bar(
                x=d['Era'],
                y=d[f'{metric}_{s}'],
                name=f'{t} {s.upper()}',
                marker_color=color,
                legendgroup=t,
                showlegend=(i==0),
                row=r, col=c
            )

# -------------------------------
# Layout
# -------------------------------
fig.update_layout(
    template='plotly_dark',
    plot_bgcolor='#0f171e',
    paper_bgcolor='#0f171e',
    font=dict(color='white'),
    height=750,
    width=1000,
    title="Amazon Prime Metrics by Era (Mean vs Q75 vs Max)",
    title_x=0.5,
    barmode='group',
    legend=dict(orientation="h", y=0.5, x=0.5, xanchor="center")
)

fig.show()

"""##### 1. Why did you pick the specific chart?

**`2x2 Grouped Bar chart:`** Is a ideal chart to summarize category vs category distribution , specifically release year era with diffrent categorical variables.

##### 2. What is/are the insight(s) found from the chart?

**`Runtime w.r.t Era:`**
- *`Movies:`* Average 95 || 75% = 120 minutes.
- *`TV Show:`* Average 40 || 75% = 55 minutes.

**`AMprime Score w.r.t Era :`**
- *`Movies:`* Average 6 ||  75%  upto < 7.
- *`TV Show:`* Average 7 || 75% upto 8.

**`AMprime Popularity w.r.t Era:`**
- *`Movies:`* Average 2.5 and 75% upto 3-3.5.
- *`TV Show:`* Average 2.2 and 75% upto 2.8.

**`AMprime Rating w.r.t Era:`**
- *`Movies:`* Average  4.4 ||  75% = 5.
- *`TV Show:`* Average 5.2 || 75% upto 5.7.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Movies runtime idealy shuld be between `120 minutes or can take +- 20 minutes`
- TV show runtime idealy shuld be between `45 minutes or can be +- 10 minutes.`
- TV Shows are more like by croud then Movies as seen in are insights.
- AMprime Score: should be around `IBDB & TMDB6-7.5`
- AMprime Popularity: should be around `IBDB & TMDB `
 - mean	2.222742e+04 to 10.185078 to 75% =6.359000e+03 to	8.803000
- AMprime Rating: should be around

**`AMprime_score:`** is equal `blend of (imdb score & tmdb score)`
  
  That give blended movies satisfactory and authantication score from both major online databases.

**`AMprime Popularity:`** is blend of `( imdb_votes = 2.222742e+04 & tmdb_popularity= 10.185078)`

That give blended movies satisfactory and authentic votes and polularity result from both major online databases.

**`AMprime Rating:`**  is blend of `(60% weight of imdb_votes & 40% weight of AMprime Popularity)`
That give blended of satisfactory and authentic score, votes and polularity result from both major online databases.

#### Chart - 7
"""

# Chart - 6 visualization
#---------------------------------------------------------------------------------------------
# Multiploat matrix AMprimE features with (Era, Content Quality, Runtime Category, Popularity)
#---------------------------------------------------------------------------------------------

def plot_multi_analysis(df, value_col, title_name):

    df = df.copy()

    # Aggregations
    era_df = df.groupby(['Era','type'])[value_col].mean().reset_index()
    runtime_df = df.groupby(['runtime_category','type'])[value_col].mean().reset_index()

    colors = {'MOVIE': '#00A8E1', 'SHOW': '#FF9900'}

    fig = make_subplots(
        rows=2, cols=2,
        subplot_titles=(
            f"Bar: {title_name} vs Era",
            f"Box: {title_name} vs Content Quality",
            f"Line: {title_name} vs Runtime Category",
            f"Scatter: {title_name} vs Popularity"
        )
    )

    # Loop once for all plots
    for t in ['MOVIE', 'SHOW']:

        d_main = df[df['type'] == t]
        d_era = era_df[era_df['type'] == t]
        d_run = runtime_df[runtime_df['type'] == t]

        # Bar
        fig.add_bar(x=d_era['Era'], y=d_era[value_col],
                    name=t, marker_color=colors[t],
                    legendgroup=t, showlegend=True,
                    row=1, col=1)

        # Box
        fig.add_box(x=d_main['Content_Quality'], y=d_main[value_col],
                    name=t, marker_color=colors[t],
                    legendgroup=t, showlegend=False,
                    row=1, col=2)

        # Line
        fig.add_scatter(x=d_run['runtime_category'], y=d_run[value_col],
                        mode='lines+markers',
                        name=t,
                        line=dict(color=colors[t], width=3),
                        legendgroup=t, showlegend=False,
                        row=2, col=1)

        # Scatter
        fig.add_scatter(x=d_main['AMprime_Popularity'], y=d_main[value_col],
                        mode='markers',
                        name=t,
                        marker=dict(color=colors[t], size=6, opacity=0.6),
                        legendgroup=t, showlegend=False,
                        row=2, col=2)

    # Layout
    fig.update_layout(
        template='plotly_dark',
        plot_bgcolor='#0F171E',
        paper_bgcolor='#0F171E',
        font=dict(color='#E6F1F5'),
        height=700,
        width=1000,
        title=f"{title_name} Analysis Across Categories",
        title_x=0.5,
        legend=dict(orientation="h", y=0.5, x=0.5, xanchor="center")
    )

    fig.show()

# AMprime_Score Matrix
plot_multi_analysis(Amazon_Prime, 'AMprime_Score', 'AMprime Score')

"""##### 1. Why did you pick the specific chart?

-  `Bar chart:` For chart is ideal chart for to see the distribution of cetegory of release year yeara.
- `Box plot:` Ideal to know distribution of categories outliers as used in content quality.
- `Line chart:` Mostly line chart is used for trend over time,but here runtime category distribution by AMprime Ratting.
- `Scatter plot:` is used for know relation between 2 numeric column.

##### 2. What is/are the insight(s) found from the chart?

1) `Era:` In each Era's AMprime Score (IMDb + TMDb score) are seems equally distributed for Movies=5.9~ and TV Shows= 7-7.5.

2) `Content quality:` `AMprime Rating` = `60% (AMprime Score(IMDb + TMDb score))` & `40% (AMprime Popularity(IMDb vots + TMDb polularity))`

- Poor: Movies --> Mean = ~6. || Shows --> Mean = ~7.
- Average: Movies --> Mean = ~7. || Shows --> Mean = ~8.
- Good: Movies: Mean --> ~7.9.|| Shows --> Mean = ~8.5.
3) `Runtime Category:`
- Long Category: Movies--> mean = 6.6 || Shows --> Mean = 7.1
- Sort Category: mean = 5.5 || Shows --> Mean = 7.1
- Averge Category: mean = 6 || Shows --> Mean = 7.3
4) `Popularity:`
- `Movies:` No strong corelation between AMprime Rating vs TMDb Populularity.  
Dense cluster around:
Popularity: ~1 to 4
Rating: ~5 to 8
👉 Majority of content is average to good, not extreme
- `TV Shows:` Most Shows Have High Ratings
Dense cluster around:
Rating: 7 to 8.5
👉 TV shows are generally consistently well-rated

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

📈 Positive Business Impact

1)Focus on High-Quality Shows
- Shows consistently have higher AMprime scores (~7–8.5)
- 👉 Investing in TV shows can increase user retention and satisfaction

2)Promote “Good Quality” Content
- Content labeled Good has highest and stable scores
- 👉 Prioritizing such content improves platform credibility

3)Leverage Popular Content
- Slight positive link between popularity & score
- 👉 Promoting trending content can boost engagement

`📉 Insights Leading to Negative Growth`

1)High Variability in Movies
- Movies show wide score spread (low to high)
- 👉 Risk of inconsistent user experience → churn risk

2)Poor Quality Content Drags Down Ratings
- “Poor” category has very low scores (1–5)
- 👉 Can damage brand perception if not filtered

#### Chart - 8
"""

# Chart -8 visualization code
#----------------------------------------------------
# Reusable Function (dynamic metric)
#----------------------------------------------------

def prepare(df, col, value_col):

    df = df.explode(col)
    df = df[df[col] != ""]

    # reduce clutter
    top = df[col].value_counts().head(10).index
    df = df[df[col].isin(top)]

    agg = (
        df.groupby([col, 'type'])[value_col]
        .agg(
            Mean='mean',
            Q1=lambda x: x.quantile(0.25),
            Q3=lambda x: x.quantile(0.75)
        )
        .reset_index()
    )

    agg['Upper'] = agg['Q3'] + 1.5 * (agg['Q3'] - agg['Q1'])

    agg = agg.melt(
        id_vars=[col, 'type'],
        value_vars=['Mean', 'Q3', 'Upper'],
        var_name='Metric',
        value_name='Score'
    )

    agg['Label'] = agg['type'] + " | " + agg['Metric']

    order = (
        df.groupby(col)[value_col]
        .mean()
        .sort_values(ascending=False)
        .index
    )

    return agg, order


# ----------------------------------------------------
# Plot Function
# ----------------------------------------------------
def plot_metric(value_col, title_name):

    country_df, country_order = prepare(
        Amazon_Prime, 'production_countries', value_col
    )

    genre_df, genre_order = prepare(
        Amazon_Prime, 'genres', value_col
    )

    # Strong contrast colors
    colors = {
    # MOVIES → Blue shades
    'MOVIE | Mean':  '#37E8C1',
    'MOVIE | Q3':    '#B03CE8',
    'MOVIE | Upper': '#3588E4',

    # SHOWS → Orange shades
    'SHOW | Mean':   '#DE9632',
    'SHOW | Q3':     '#0C9E26',
    'SHOW | Upper':  '#EEB182'
}

    # ------------------------------------------------
    # Subplots
    # ------------------------------------------------
    fig = make_subplots(
        rows=1, cols=2,
        subplot_titles=("Production Countries", "Genres"),
        horizontal_spacing=0.12
    )

    # ------------------------------------------------
    # Add Bars
    # ------------------------------------------------
    for label in country_df['Label'].unique():

        # Countries
        d1 = country_df[country_df['Label'] == label]

        fig.add_bar(
            x=d1['Score'],
            y=d1['production_countries'],
            orientation='h',
            name=label,
            marker=dict(
                color=colors[label],
                line=dict(color='white', width=0.5)
            ),
            width=0.22,   # thicker bars
            legendgroup=label,
            showlegend=True,
            row=1, col=1
        )

        # Genres
        d2 = genre_df[genre_df['Label'] == label]

        fig.add_bar(
            x=d2['Score'],
            y=d2['genres'],
            orientation='h',
            name=label,
            marker=dict(
                color=colors[label],
                line=dict(color='white', width=0.5)
            ),
            width=0.22,
            legendgroup=label,
            showlegend=False,
            row=1, col=2
        )

    # ------------------------------------------------
    # Axis Order
    # ------------------------------------------------
    fig.update_yaxes(
        categoryorder='array',
        categoryarray=country_order,
        row=1, col=1
    )

    fig.update_yaxes(
        categoryorder='array',
        categoryarray=genre_order,
        row=1, col=2
    )

    # ------------------------------------------------
    # Layout
    # ------------------------------------------------
    fig.update_layout(
        template='plotly_dark',
        plot_bgcolor='#0F171E',
        paper_bgcolor='#0F171E',
        font=dict(color='white'),

        title=f"{title_name} Analysis Bottom (Mean vs Q3 vs Upper Bound)",
        title_x=0.5,

        barmode='group',

        # spacing
        bargap=0.55,
        bargroupgap=0.3,

        height=750,
        width=1100,

        legend=dict(
            orientation='h',
            y=-0.18,
            x=0.5,
            xanchor='center'
        )
    )

    fig.show()

# AMprime_Score relation with (Genres & Production Countries)
plot_metric('AMprime_Score', 'AMprime Score')

"""##### 1. Why did you pick the specific chart?

**`(1x2) Horizontal Clustered Bar Chart:`** Ideal chart to represent distribution of AMprime Score on x-axis w.r.t represent different group of Production countries & genres on a y-axis. That provide a clear indication of score pattern.

##### 2. What is/are the insight(s) found from the chart?

`Production counteries:`
- Movies: mean = 6.2 || Q.75= 6.8 to 7.2
- TV Shows: mean = around 7.3 , Q.75 = around 7.8 to 8.

`Genres:`
- Movies: mean =  around 5.8 || Q.75= 6.6
- TV Shows: mean = around 7.4 , Q.75 = around 7.8 to 8.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**`Positive`**

TV Shows are more dominant than Movies with respect to gaining AMprime Score.
With these genres and production countries,
By investing in such top production countries in combination with these top genres, as seen in the graph, the platform can engage customers and achieve huge positive growth in terms of customer engagement and ROI.

**`Negative`**

Most countries are not major producers of TV Shows.
Movies tend to have a lower average AMprime Score (around 6), which can become a reason for customer churn.
There is a need to develop an effective strategy to improve performance in low-production countries and underperforming genres.

#### Chart - 9
"""

# Chart - 9 visualization code
# AMprime Popularity Matrix
plot_multi_analysis(Amazon_Prime, 'AMprime_Popularity', 'AMprime Popularity')

"""##### 1. Why did you pick the specific chart?

**`2×2 Subplots:`**

- **Bar chart:** This chart is ideal for visualizing the distribution of categories across release years.
- **Box plot:** Ideal for understanding the distribution of categories and identifying outliers, as used in content quality.
- **Line chart:** Mostly used for trends over time, but here it is used to show runtime category distribution by AMPrime popularity.
- **Scatter plot:** Used to understand the relationship between two numeric columns.

##### 2. What is/are the insight(s) found from the chart?

1) `Era:` In each Era's AMprime Popularity (IMDb Vots + TMDb Popularity) for Movies= ~2.4 and TV Shows= 2.3. hence almostc equaly distribution.

2) `Content quality:`
- Poor: Movies --> Mean = ~2. || Shows --> Mean = ~2.
- Average: Movies --> Mean = ~3.3. || Shows --> Mean = ~2.8.
- Good: Movies: Mean --> ~5 || Shows --> Mean = ~5.4.
3) `Runtime Category:`
- Long Category: Movies--> mean = 2.8 || Shows --> Mean = 2.2
- Sort Category: mean = 1.8 || Shows --> Mean = 2.06
- Standard Category: mean = 2.5 || Shows --> Mean = 2.4
4) `Popularity:`
- `Movies:` Strong directly propotional corelation between AMprime Popularity vs TMDb Populularity for both movies and TV shows.
- `TV Shows:` Strong relation , bot have outlier after a cetrain point 4.3.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**`Positive:`**

- Movies are more popular than TV Shows, but TV Shows show consistent popularity growth across eras.
- Movies have higher average content quality compared to TV Shows.
- As the runtime increases, popularity also increases, especially for Movies.
- AMprime Popularity is proportional to TMDb Popularity for both Movies and TV Shows.

**`Negative:`**

- Popularity has reduced in the Classic, Modern, and Recent eras, possibly because TV Shows are becoming more preferred due to shorter, binge-friendly content, while Movies are often one-time watch experiences.
- The distribution of content quality (Good, Average, Poor) is becoming more evenly spread, indicating no strong quality differentiation.
- TV Shows perform well in terms of scores, but their popularity is still lower than Movies.
- Overall, TV Shows are less popular than Movies when considering combined IMDb votes and TMDb popularity.

#### Chart - 10
"""

# Chart - 10 visualization code
# AMprime Popularity relation with (Genres & Production Countries)
plot_metric('AMprime_Popularity', 'AMprime Popularity')

"""##### 1. Why did you pick the specific chart?

**`(1x2) Horizontal Clustered Bar Chart:`** Ideal chart to represent distribution of AMprime Popularity on x-axis w.r.t represent different group of Production countries & genres on a y-axis. That provide a clear indication of score pattern.

##### 2. What is/are the insight(s) found from the chart?

`Production counteries:`
- Movies: mean = 2.6 || Q.75= 3.1 to 3.3
- TV Shows: mean = 2.4 to 2.6 , Q.75 = around 2.4 to 2.6.

`Genres:`
- Movies: mean =  around 2.4 to 2.7 || Q.75= 3 to 3.3
- TV Shows: mean = around 2.1 to 2.3 , Q.75 = around 2.6 to 2.8.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**`Positive:`**
These production countries and genres are in the top 20, so the platform can focus on promoting and investing in them.

-      Movies: The average mean is around 2.4 to 2.7, and the top 25% (Q75) is around 3 to 3.3.
-      TV Shows: The average mean is around 2.4 (±0.2), and Q75 is around 2.6 (±0.2).

- This shows that Movies have slightly higher peak popularity, while TV Shows are more stable.

- Combining these top genres with top production countries can improve ***customer engagement.*** Using this combination strategy can help increase overall growth for both Movies and TV Shows.

**`Negative:`**

- Popularity growth is more driven by Movies than TV Shows, because only a few countries are producing most of the TV Shows.

- This creates a risk, as the platform depends on limited regions for TV content.

- Also, genres and production countries with popularity below 2 should be avoided, because they bring low engagement and low ROI.

#### Chart - 11
"""

# Chart - 11 visualization code
# AMprime Rating Matrix
plot_multi_analysis(Amazon_Prime, 'AMprime_Rating', 'AMprime Rating')

"""##### 1. Why did you pick the specific chart?

**`2×2 Subplots:`**

- **Bar chart:** This chart is ideal for visualizing the distribution of categories across release years.
- **Box plot:** Ideal for understanding the distribution of categories and identifying outliers, as used in content quality.
- **Line chart:** Mostly used for trends over time, but here it is used to show runtime category distribution by AMPrime popularity.
- **Scatter plot:** Used to understand the relationship between two numeric columns.

##### 2. What is/are the insight(s) found from the chart?

1) `Era:` In each Era's AMprime Rating (AMprime (Score + Popularity)), Movies = ~4.4 (±0.2) and TV Shows = 5.3 (±0.2). Hence, TV Shows are gaining more Ratings than Movies.
2) `Content quality:`
- Poor: Movies --> Mean & Q75 = ~4.1 & 4.5 || Shows --> Mean & Q75 = ~5 & 5.2

   `Quality Range:`
    1) Movies:  below 4.3
    2) TV Shows:  below 5
- Average: Movies --> Mean & Q75 = ~5.4 & 4.8 || Shows--> Mean & Q75 = ~5.8 & 6.2.

   `Quality Range:`
   1) Movies:  between 5 to 6.4
   2) TV Shows:  between 5.5 to 7
- Good: Movies: Mean & Q75--> ~6.7 & 6.9 || Shows --> Mean & Q75 = ~7.3.

   `Quality Range:`
   1) Movies:  between 5 - 6.4
   2) TV Shows:  between 7 - 7.5
3) `Runtime Category:`
- Long Category: Movies--> mean = 5 || Shows --> Mean = 5.2
- Sort Category: Movies--> mean = 4 || Shows --> Mean = 5.1
- Standard Category: Movies--> mean = 4.6 || Shows --> Mean = 5.3 (+0.1)

> `Means:` movies: As long runtime have much high Rating

> `TV Shows:` Standerd runtime tends to have gaining highest rating.

4)`Popularity:`
- `Movies:`
  1) A cluster of Movies is kept within the range of Popularity & AMprime Rating (x = 0:4, y = 0:6).
  2) Movies trying to exceed Popularity more than 4 are proportional to gaining an AMprime Rating greater than 6.
- `TV Shows:`
  1) Positive correlation between Popularity and Rating.
  2)A small cluster of TV Shows is gathered within the range of Popularity & AMprime Rating ~(x = 1.5:3.5, y = 4:6). That is significant of most TV Shows' Rating behaviour across Popularity
  3) A tiny cluster of TV Shows has Ratings above 6 and Popularity above 4.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**`Positive:`**
- The count of TV Shows are very less, but ratings are significantly much higher than Movies in each era.
- Same with Content Quality, TV Shows count is very low, but ratings are much higher.
  - Investors should invest in TV Show production, hence they have much scope in scoring and customer engagement.

  -Standard runtime is the ideal runtime for TV Shows to gain their highest ratings.
  - While for Movies, long runtime is the ideal factor to achieve highest ratings.

- In scatter plot, Movies almost cover 3 times more graph area compared to TV Shows, and the range between (x, y) for Movies = (0:5, 2:6)
- While TV Shows range between (0:5, 4:6), hence the count is less for TV Shows. That is a significant sign of delivering higher rating content quality by TV Shows with more consistency and accuracy.

**`Negetive:`**
- Movie ratings are reducing era by era. Old era Movies had the highest peak ratings, but after that ratings are getting slightly reduced in each era. Hence, Modern and Recent eras have lower ratings compared to `Old to Early 2000's era`. That is a negative sign for Movies future growth.
  - Hence, Movies need proper strategies that can maintain or increase ratings.
- The count of Poor Content is much higher than Average and Good Content. This leads to negative growth.

- The count of TV Shows is less, but they have the highest significance in customer engagement.
   - Investors should invest more in TV Shows, as it is the highest significant factor for customer engagement.

#### Chart - 12
"""

# Chart - 11 visualization code
# AMprime Rating relation with (Genres & Production Countries)
plot_metric('AMprime_Rating', 'AMprime Rating')

"""##### 1. Why did you pick the specific chart?

**`(1x2) Horizontal Clustered Bar Chart:`** Ideal chart to represent distribution of AMprime Rting on x-axis w.r.t represent different group of Production countries & genres on a y-axis. That provide a clear indication of score pattern.

##### 2. What is/are the insight(s) found from the chart?

`Production counteries:` (+-0.2)
- Movies: mean = 4.7 || Q.75= 5.3 || Upper= 6.8
- TV Shows: mean = 5.2 , Q.75 = 5.7 || Upper = 6.7

`Genres:` (+-0.2)
- Movies: mean = 4.6 || Q.75= 5.1 || Upper = 7
- TV Shows: mean = 5.4 || Q.75 = 5.8  || Upper = 7.2

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**`Positive:`**
- As confirmed multiple times through various graphs, TV Shows are performing better compared to Movies.
- These are the Top 10 production countries  || Genres that are highly qualified in terms of maintaining the highest ratings among all production countries & Genres.
  - *`Production countries:`* Canada (Ca) | USA | Italy (It) | India | Australia (Au) | UK | Germany (De) | Japan (Jp) | France (Fr) | China (Cn)
  - *`Genres:`* Horror | SciFi | Action | Comedy | Thriller | Romance | Crime | Drama | Fantasy | European
- The combination of these countries and genres can help increase customer engagement.
- Strategically, if these countries collaborate with lower-income countries for movie or TV show production, it can significantly reduce production costs while maintaining high content quality. Through this strategy, lower-segment countries may also gradually develop their own content industry and become a future source of audience growth from their regions.

**`Negetive:`**
- The count of Movies is much higher, but their ratings are still low. This may lead to negative growth for Movies in the future. Hence, there is a need to focus on increasing movie popularity
-Avoid producing Movies in low-rated genres. Instead, it would be a more effective approach to use these genres for TV Shows, as this can increase their popularity and customer engagement. Examples include
   - Family | Western | History | Documentation | Music | War | Animation | Sport | Reality
- For low-rating production countries, collaboration with developed countries can be an effective strategy to improve content quality, audience reach, and overall growth.

#### Chart - 13
"""

# Chart - 12 visualization code
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=("Rating vs Score", "Rating vs Popularity")
)

colors = {
    'MOVIE': '#00A8E1',
    'SHOW': '#FF9900'
}

def add_scatter_with_trend(x, y, col):

    for t in ['MOVIE', 'SHOW']:
        df = Amazon_Prime[Amazon_Prime['type'] == t]

        temp_fig = px.scatter(
            df,
            x=x,
            y=y,
            trendline="ols"
        )

        for trace in temp_fig.data:

            if trace.mode == 'markers':
                trace.marker.update(
                    size=4,
                    color=colors[t],
                    opacity=0.25
                )
                trace.name = t
                trace.legendgroup = t
                trace.showlegend = (col == 1)

            else:
                # MAIN LINE
                trace.line.update(
                    color=colors[t],
                    width=4
                )

                # (duplicate line)
                fig.add_trace(
                    dict(
                        type='scatter',
                        x=trace.x,
                        y=trace.y,
                        mode='lines',
                        line=dict(color='white', width=7),
                        opacity=0.15,
                        showlegend=False
                    ),
                    row=1, col=col
                )

                trace.name = f"{t} Trend"
                trace.legendgroup = t
                trace.showlegend = False

            fig.add_trace(trace, row=1, col=col)

# Add plots
add_scatter_with_trend('AMprime_Score', 'AMprime_Rating', 1)
add_scatter_with_trend('AMprime_Popularity', 'AMprime_Rating', 2)

# Layout
fig.update_layout(
    template='plotly_dark',
    plot_bgcolor='#0b141a',
    paper_bgcolor='#0b141a',
    font=dict(color='#e6f1f5'),

    height=500,
    width=1000,

    title="Prime Video Analytics: Rating vs Score & Popularity",
    title_x=0.5,

    legend=dict(
        orientation="h",
        y=1.05,
        x=0.5,
        xanchor="center"
    )
)

fig.update_xaxes(showgrid=False)
fig.update_yaxes(gridcolor='rgba(255,255,255,0.05)')

# Log scale
fig.update_xaxes(type="log", row=1, col=2)

fig.show()

"""##### 1. Why did you pick the specific chart?

**`Scatter plot:`** An ideal graph to show the relationship between numeric vs numeric variables, especially the relation between AMprime Rating with Score and Popularity.

##### 2. What is/are the insight(s) found from the chart?

1) **`AMprime Rating vs Score:`**
- High  linear relationship for both Moives and TV Shows.
- Data points are closealy packed with trending line, that indicate strong relation in both.

2) **`AMprime Rating vs Popularity:`**
- There is *moderate positive relationship* between AMprime Rating and AMprime Popularity
- The wider spread of points indicates that higher popularity does not always guarantee a higher rating, although it still positively influences the final AMprime Rating.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Users get more feasible and reliable recommendations with higher content quality, which can improve overall user experience.

**`AMprime Score`**

- Mean of (IMDb Score + TMDb Score)

Used to provide more trustworthy and high-quality content recommendations by combining the scoring systems of both IMDb and TMDb platforms.

**`AMprime Popularity:`**

- Mean of (IMDb Votes + TMDb Popularity)

Used to provide more reliable and audience-based popularity measurement by combining IMDb Votes and TMDb Popularity metrics.

**`AMprime Rating:`**

A combined metric created using:

- 60% AMprime Score
- 40% AMprime Popularity

This approach helps provide more feasible and high-quality content recommendations by balancing both:

- Content Quality → AMprime Score (IMDb Score + TMDb Score)
- Audience Engagement & Popularity → AMprime Popularity (IMDb Votes + TMDb Popularity)

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code
# Correlation matrix
corr = Amazon_Prime.select_dtypes(include='number').corr()

# Plot
fig = px.imshow(
    corr,
    text_auto=True,
    aspect="auto",
    color_continuous_scale='RdBu_r'
)

# Amazon Prime dark theme styling
fig.update_layout(
    title="Amazon Prime - Correlation Heatmap",
    template="plotly_dark",
    paper_bgcolor="#0F171E",   # Prime dark background
    plot_bgcolor="#0F171E",
    font=dict(color="white")
)

fig.show()

"""##### 1. Why did you pick the specific chart?

**`Heatmap:`**
A Pair Plot / Correlation Graph is a popular graph used to show the cross-correlation between all numeric variables and helps identify the strength or percentage of correlation among them.

##### 2. What is/are the insight(s) found from the chart?

**`Very Strong Positive Correlation (0.80 - 1.00)`**
- AMprime_Score ↔ AMprime_Rating = 0.91
- `tmdb_score` ↔ (`AMprime_Score = 0.90`,
`AMprime_Score = 0.89`,
`AMprime_Rating = 0.82`,
`AMprime_Rating = 0.81`)

**`Strong Positive Correlation (0.60 - 0.79)`**
- AMprime_Popularity ↔ AMprime_Rating = 0.71
- imdb_score ↔ tmdb_score = 0.61

**`Moderate Positive Correlation (0.40 - 0.59)`**
- `imdb_votes` ↔ (`AMprime_Popularity = 0.55`, `AMprime_Rating = 0.44`

**`Weak Positive Correlation (0.20 - 0.39):`
- tmdb_popularity ↔ AMprime_Popularity = 0.38
- AMprime_Score ↔ AMprime_Popularity = 0.36
- imdb_score ↔ AMprime_Popularity = 0.34
- runtime ↔ AMprime_Popularity = 0.30
- tmdb_score ↔ AMprime_Popularity = 0.30
- imdb_votes ↔ AMprime_Score = 0.27
- imdb_score ↔ imdb_votes = 0.26
- tmdb_popularity ↔ AMprime_Rating = 0.25
- imdb_votes ↔ tmdb_popularity = 0.23
- runtime ↔ imdb_votes = 0.21
- imdb_votes ↔ tmdb_score = 0.22

**`Very Weak / No Correlation (0.00 - 0.19)`**
- Most relations with release_year
- runtime ↔ imdb_score
- runtime ↔ tmdb_score
- tmdb_popularity ↔ imdb_score
- tmdb_popularity ↔ tmdb_score

**`Negative Correlation`**
- release_year ↔ imdb_score = -0.03 (Very Weak Negative Correlation)

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code
# Load dataset
# Load dataset
df = Amazon_Prime.copy()

# Columns
cols = [
    'imdb_score',
    'tmdb_score',
    'tmdb_popularity',
    'imdb_votes',
    'AMprime_Score',
    'AMprime_Popularity',
    'AMprime_Rating'
]

# --- Clean 'type' column ---
df['type'] = df['type'].astype(str).str.strip().str.upper()

# --- Drop missing values ---
df_clean = df[cols + ['type']].dropna()

# --- Dynamic color mapping ---
unique_types = df_clean['type'].unique()
colors = ['#00A8E1', '#1CE783', '#FF9900', '#E50914']
color_map = dict(zip(unique_types, colors[:len(unique_types)]))

# --- Plotly Pair Plot ---
fig = px.scatter_matrix(
    df_clean,
    dimensions=cols,
    color='type',
    color_discrete_map=color_map,
    opacity=0.6,
    title="Amazon Prime Pair Plot"
)

# --- Remove diagonal plots ---
fig.update_traces(diagonal_visible=False)

# --- Styling ---
fig.update_layout(
    template='plotly_dark',
    paper_bgcolor='#0F171E',
    plot_bgcolor='#0F171E',
    font=dict(color='white', size=10),
    title_font=dict(size=22, color='#00A8E1'),

    # Increase size to avoid overlap
    width=1000,
    height=1000,

    # Better spacing
    margin=dict(l=80, r=80, t=100, b=80)
)

# --- Fix overlapping variable names ---
fig.update_xaxes(
    tickangle=45,
    automargin=True
)

fig.update_yaxes(
    automargin=True
)

fig.show()

"""##### 1. Why did you pick the specific chart?

**`Pair plot:`**
A Pair Plot is a popular graph used to show the cross-correlation between all numeric variables with scater and histogram that helps identify the relation between cross nueric variable and used in ml model.

##### 2. What is/are the insight(s) found from the chart?

- Strong positive correlation between IMDb Score, TMDb Score, AMprime Score, and AMprime Rating.
- AMprime Score has the strongest impact on AMprime Rating.
- IMDb Votes and TMDb Popularity show a moderate positive relationship with Rating.
- TMDb Popularity and IMDb Votes contain several outliers.
- Movies show a wider spread in performance compared to TV Shows.
- TV Shows maintain more consistent and higher ratings.
- Popularity variables show a non-linear relationship with Rating.
- AMprime metrics effectively combine content quality and popularity into a balanced rating system

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

Our business objective is to enhance customer experience by providing high-quality Movies and TV Shows, which directly helps increase customer and viewer engagement on the platform. In this context, we discovered several key insights that are directly related to improving customer satisfaction and enhancing overall user experience.

For stakeholders, we identified multiple business ideas that can create a positive impact on customer engagement and platform growth. We also discovered certain insights that may lead to negative growth and could potentially affect the overall user experience if not addressed properly.

----------------------------------------------------------------------------------------------------------------------------------------------------------------

###**`Factor 1:`**
----------------------------------------------------------------------------------------------------------------------------------------------------------------
First, The count of TV Show is almost 3 to 4 time less, but there are more populer to gain IMDb and TMDb scrors , vots and popularity.

- Production countries:
  1) Top Countries in production:
    - USA • UK • India • Canada • France • Germany • Japan • Italy • Australia • China
  2) Middle 10 Production Countries
    - Venezuela  • Egypt  • Turkey  • Bolivia  • Qatar  • Singapore  • Croatia  • Lebanon • Bulgaria • Pakistan
  3) Bottom Production Countries
    - Cameroon • Fiji • Turks •  Caicos Islands • Equatorial Guinea • Bangladesh • Libya • Antarctica • Paraguay • Dominican Republic • French Polynesia  
- Genres:
  1) Top Genres:
    - Drama • Comedy • Thriller • Action • Romance • Crime • Horror • European • SciFi • Fantasy
  2) Middle Genres:
    - • Western •  Family • Romance  • Documentation • History  
  3) Bottom Genres:
    - • Music • Sport • Reality • Documentation • Animation • War • History     

**Business Growth Ideas**
1) **`Top Segment:`**
- All top countries are performing very well with top genres. There is no major need to focus heavily on this segment, as they are already generating outstanding customer engagement and ROI.
2) **Middle Segment:`**
- These countries have strong future growth potential. A smart strategy would be to collaborate top production countries with these regions through smaller investments and regional partnerships. This can help the platform easily capture these markets, improve customer engagement, and achieve better ROI and market expansion.
3) **`Bottom Segment:`**
- Higly risky to invest in this segment low chances to get ROI. But stretgecly
Cloabration will work for future prospect, we can suggestion to **Top Segment** to make their TV Show and Movies this region (countries) and give supporting rols to these region actors. That get audience from this region as well, and definaly get good ROI. But it will be cost effective to make movies and shows in this region for top counteies.

----------------------------------------------------------------------------------------------------------------------------------------------------------------

###**`Factor 2:`**
----------------------------------------------------------------------------------------------------------------------------------------------------------------

- Avoid producing Movies in bottom genres, as this can be highly risky and may lead to significant negative growth. Some middle-category genres may also perform poorly in Movies.

- Middle and bottom genres are not ideal for Movies, but they are gaining better scores and popularity in TV Shows. Hence, it would be a smart strategy to focus in these genre categories to make..
   - TV Shows
   - web series
   - mini-series
- This balanced approach can help normalize the scores and popularity of these genres while improving customer engagement and platform growth.

----------------------------------------------------------------------------------------------------------------------------------------------------------------
###**`Factor 3:`**
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 **`Runtime Fctor:`**
 Ideal runtime for
- **`Movies:`** Standerd to Long runtime is ideal runtime for movies rating, score and ganing popularity. (above 150 miutes)
- **`TV Shows:`** Standerd runtime for ideal segnificent for gaining rating and score. range between (45-60 minutes).

----------------------------------------------------------------------------------------------------------------------------------------------------------------

###**`Factor 4:`**
----------------------------------------------------------------------------------------------------------------------------------------------------------------

- TV Shows have a lower content count, but they show significantly higher overall scores, popularity, and rating performance.
- Poor-quality content has a high impact on the overall rating system.
   - Poor: Movies mean = 4.5 (score + rating)
- The overall scoring system is more favorable for TV Show growth.
- The overall popularity system is more favorable for Movie growth.
- Considering all factors together, TV Shows show stronger overall growth potential.
----------------------------------------------------------------------------------------------------------------------------------------------------------------

###**` Factor 5:`**
----------------------------------------------------------------------------------------------------------------------------------------------------------------

Users get more feasible and reliable recommendations with higher content quality, which can improve overall user experience.

- **`AMprime Score`**

   - Mean of (IMDb Score + TMDb Score)

Used to provide more trustworthy and high-quality content recommendations by combining the scoring systems of both IMDb and TMDb platforms.

- **`AMprime Popularity:`**

   - Mean of (IMDb Votes + TMDb Popularity)

Used to provide more reliable and audience-based popularity measurement by combining IMDb Votes and TMDb Popularity metrics.

- **`AMprime Rating:`** A combined metric created using:
  -  60% AMprime Score
  - 40% AMprime Popularity

This approach helps provide more feasible and high-quality content recommendations by balancing both:

- Content Quality → AMprime Score (IMDb Score + TMDb Score)
- Audience Engagement & Popularity → AMprime Popularity (IMDb Votes + TMDb Popularity)

----------------------------------------------------------------------------------------------------------------------------------------------------------------

# **Conclusion**

The objective of this project was to improve customer experience and viewer engagement on the OTT platform through data-driven analysis of Movies and TV Shows.

The analysis shows that TV Shows have stronger overall growth potential, with better ratings, scores, engagement, and popularity stability compared to Movies. Top production countries and genres are already generating high ROI and customer engagement, while middle-segment countries provide strong future growth opportunities through regional partnerships and strategic investments.

Also found that many middle and bottom genres perform better in TV Shows, web series, and mini-series rather than Movies. Therefore, focusing these genres on episodic content would be a smarter business strategy.

Overall, the insights from this project can help OTT platforms improve customer satisfaction, engagement, content strategy, global reach, and long-term business growth

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""

def plot_top10_by_metric(df, metric):

    # -------------------------------
    # Prepare Data
    # -------------------------------
    data = df[['name', 'type', metric]].dropna().copy()
    data['type'] = data['type'].str.strip().str.upper()

    # -------------------------------
    # Top 10 Movies & Shows
    # -------------------------------
    top_movies = data[data['type'] == 'MOVIE'].nlargest(10, metric)
    top_shows  = data[data['type'] == 'SHOW'].nlargest(10, metric)

    top_combined = pd.concat([top_movies, top_shows])

    # -------------------------------
    # Sort for correct ranking
    # -------------------------------
    top_combined = top_combined.sort_values(by=metric, ascending=True)

    # -------------------------------
    # New Custom Colors
    # -------------------------------
    color_map = {
        'MOVIE': '#2EC4B6',   # Teal
        'SHOW': '#9D4EDD'     # Purple
    }

    # -------------------------------
    # Plot
    # -------------------------------
    fig = px.bar(
        top_combined,
        x=metric,
        y='name',
        color='type',
        color_discrete_map=color_map,
        orientation='h',
        title=f"Top 10 Movies & Shows by {metric}"
    )

    # Keep order
    fig.update_yaxes(
        categoryorder='array',
        categoryarray=top_combined['name']
    )

    # Styling
    fig.update_layout(
        template='plotly_dark',
        paper_bgcolor='#0F171E',
        plot_bgcolor='#0F171E',
        font=dict(color='white'),
        title_x=0.5,
        height=600
    )

    fig.show()

"""#### `Top 10 Movies and TV Shows by AMprime Score`"""

plot_top10_by_metric(Amazon_Prime, 'AMprime_Score')

"""#### `Top 10 Movies and TV Shows by AMprime Popularity`"""

plot_top10_by_metric(Amazon_Prime, 'AMprime_Popularity')

"""#### `Top 10 Movies and TV Shows by AMprime Rating`"""

plot_top10_by_metric(Amazon_Prime, 'AMprime_Rating')